cc_binary(
    name = "dev",
    srcs = ["dev.cpp"],
    deps = ["@//:odin"],
)

cc_binary(
    name = "mcts_tictactoe",
    srcs = ["mcts_tictactoe.cpp"],
    copts = ["-std=c++20"],
    deps = ["@//:odin"],
)
